# Generated by Django 6.0.1 on 2026-01-29 21:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Nome único para a categoria (máx. 65 caracteres)', max_length=65, unique=True, verbose_name='Nome da Categoria')),
                ('description', models.CharField(help_text='Descrição breve da categoria (máx. 250 caracteres)', max_length=250, verbose_name='Descrição curta')),
                ('slug', models.SlugField(help_text='Versão legível para URL do nome', max_length=100, unique=True, verbose_name='Slug da URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, help_text='Título da receita (máx. 150 caracteres)', max_length=150, verbose_name='Título da receita')),
                ('description', models.CharField(help_text='Descrição breve da receita (máx. 250 caracteres)', max_length=250, verbose_name='Descrição curta')),
                ('slug', models.SlugField(help_text='Versão legível para URL do título', max_length=200, unique=True, verbose_name='Slug da URL')),
                ('preparation_time', models.PositiveIntegerField(help_text='Tempo necessário para preparar', validators=[django.core.validators.MinValueValidator(1, message='O tempo de preparo deve ser pelo menos 1'), django.core.validators.MaxValueValidator(1000, message='O tempo de preparo parece muito longo')], verbose_name='Tempo de preparo')),
                ('preparation_time_unit', models.CharField(choices=[('minutos', 'Minutos'), ('horas', 'Horas'), ('segundos', 'Segundos')], default='minutos', help_text='Unidade de medida do tempo de preparo', max_length=20, verbose_name='Unidade de tempo de preparo')),
                ('servings', models.PositiveIntegerField(help_text='Quantas porções esta receita rende', validators=[django.core.validators.MinValueValidator(1, 'Deve servir pelo menos 1 porção'), django.core.validators.MaxValueValidator(1000, 'O valor de porções parece um pouco alto')], verbose_name='Número de porções')),
                ('serving_unit', models.CharField(choices=[('porcoes', 'Porções'), ('pedacos', 'Pedaços'), ('fatias', 'Fatias'), ('unidades', 'Unidades')], default='porcoes', help_text='Unidade de medida para as porções', max_length=20, verbose_name='Unidade de porção')),
                ('cooking_time', models.PositiveIntegerField(help_text='Tempo necessário para cozinhar', validators=[django.core.validators.MinValueValidator(1, message='O tempo de cozimento deve ser pelo menos 1'), django.core.validators.MaxValueValidator(1000, message='O tempo de cozimento parece muito longo')], verbose_name='Tempo de cozimento')),
                ('cooking_time_unit', models.CharField(choices=[('minutos', 'Minutos'), ('horas', 'Horas'), ('segundos', 'Segundos')], default='minutos', help_text='Unidade de medida do tempo de cozimento', max_length=20, verbose_name='Unidade de medida de cozimento')),
                ('ingredients', models.TextField(help_text='Liste todos os ingredientes necessários (recomendado um por linha)', verbose_name='Ingredientes')),
                ('preparation_steps', models.TextField(help_text='Instruções detalhadas sobre como preparar a receita (recomendado um por linha)', verbose_name='Modo de preparo')),
                ('preparation_steps_is_html', models.BooleanField(default=False, help_text='Marque se o modo de preparo contém formatação HTML', verbose_name='Modo de preparo em HTML')),
                ('cover', models.ImageField(blank=True, help_text='Imagem principal da receita', null=True, upload_to='recipes/covers/%Y/%m/%d/', verbose_name='Imagem da capa')),
                ('is_published', models.BooleanField(db_index=True, default=False, help_text='Marque para tornar esta receita visível ao público', verbose_name='Publicado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(help_text='Autor que criou está receita', on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('category', models.ForeignKey(help_text='Categoria da receita', on_delete=django.db.models.deletion.PROTECT, related_name='recipes', to='recipes.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Recipe',
                'verbose_name_plural': 'Recipes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='Usuário que favoritou a receita', on_delete=django.db.models.deletion.CASCADE, related_name='favorite_recipes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('recipe', models.ForeignKey(help_text='Receita que foi favoritada', on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='recipes.recipe', verbose_name='Receita')),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecipeRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='Avalie de 1 a 5 estrelas', validators=[django.core.validators.MinValueValidator(1, message='A avaliação deve ser no mínimo 1'), django.core.validators.MaxValueValidator(5, message='A avaliação deve ser no máximo 5')], verbose_name='Avaliação')),
                ('comment', models.TextField(blank=True, help_text='Comentário opcional sobre a receita', null=True, verbose_name='Comentário')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='recipes.recipe', verbose_name='Receita')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ratings', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Avaliação de Receita',
                'verbose_name_plural': 'Avalicações de Receitas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['-created_at'], name='recipes_rec_created_57db65_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['is_published', '-created_at'], name='recipes_rec_is_publ_b5a4f1_idx'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['user', '-created_at'], name='recipes_fav_user_id_5d8c58_idx'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['recipe'], name='recipes_fav_recipe__f749a7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'recipe')},
        ),
        migrations.AddIndex(
            model_name='reciperating',
            index=models.Index(fields=['-created_at'], name='recipes_rec_created_168e77_idx'),
        ),
        migrations.AddIndex(
            model_name='reciperating',
            index=models.Index(fields=['rating', '-created_at'], name='recipes_rec_rating_0277a4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reciperating',
            unique_together={('user', 'recipe')},
        ),
    ]
