# Generated by Django 6.0.1 on 2026-01-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon_key',
            field=models.CharField(blank=True, default='utensils', help_text="Insira o nome do ícone da biblioteca Lucide (ex: 'fish', 'cake', 'soup').Consulte a lista em lucide.dev", max_length=20, null=True, verbose_name='Icone da Categoria'),
        ),
    ]
