# Generated by Django 6.0.1 on 2026-02-03 14:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_category_icon_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome do ingrediente (máx. 150 caracteres)', max_length=150, unique=True, verbose_name='Nome do ingrediente')),
                ('image', models.ImageField(blank=True, help_text='Imagem principal do ingrediente', null=True, upload_to='ingredients/covers/%Y/%m/%d', verbose_name='Imagem do ingrediente')),
                ('slug', models.SlugField(help_text='Versão legível da URL do nome', max_length=100, unique=True, verbose_name='Slug da URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ingrediente',
                'verbose_name_plural': 'Ingredientes',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-created_at'], 'verbose_name': 'Receita', 'verbose_name_plural': 'Receitas'},
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='preparation_steps',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='preparation_steps_is_html',
        ),
        migrations.AddField(
            model_name='recipe',
            name='difficulty_level',
            field=models.CharField(choices=[('facil', 'Fácil'), ('medio', 'Médio'), ('dificil', 'Difícil'), ('expert', 'Expert / Profissional')], default='medio', help_text='Nível de dificuldade da receita', verbose_name='Nível de dificuldade'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time_unit',
            field=models.CharField(choices=[('s', 'Segundos'), ('min', 'Minutos'), ('h', 'Horas')], default='minutos', help_text='Unidade de medida do tempo de cozimento', max_length=20, verbose_name='Unidade de medida de cozimento'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.CharField(help_text='Descrição breve da receita (máx. 500 caracteres)', max_length=500, verbose_name='Descrição curta'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='preparation_time_unit',
            field=models.CharField(choices=[('s', 'Segundos'), ('min', 'Minutos'), ('h', 'Horas')], default='minutos', help_text='Unidade de medida do tempo de preparo', max_length=20, verbose_name='Unidade de tempo de preparo'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='serving_unit',
            field=models.CharField(choices=[('porcoes', 'Porções'), ('pessoas', 'Pessoas'), ('unidades', 'Unidades'), ('fatias', 'Fatias'), ('pedacos', 'Pedaços'), ('copos', 'Copos'), ('tacas', 'Taças'), ('pratos', 'Pratos'), ('un', 'Itens'), ('docinhos', 'Docinhos (Cento)'), ('salgadinhos', 'Salgadinhos (Cento)'), ('massa', 'Massa (kg)'), ('rendimento_livre', 'A gosto')], default='porcoes', help_text='Unidade de medida para as porções', max_length=20, verbose_name='Unidade de porção'),
        ),
        migrations.CreateModel(
            name='RecipeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Ex: Massa, Recheio, Cobertura...', max_length=100, verbose_name='Nome da Seção')),
                ('preparation_steps', models.TextField(help_text='Dica: Escreva UM passo por linha.', verbose_name='Modo de Preparo')),
                ('position', models.PositiveIntegerField(default=0, help_text='Defina a posição de suas seções. Ex: Seção 1 ( posição 0 ), Seção 2 ( posição 1 )...', validators=[django.core.validators.MinValueValidator(0, message='A posição da seção deve ser maior ou igual 0')], verbose_name='Ordem')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='recipes.recipe', verbose_name='Receita')),
            ],
            options={
                'verbose_name': 'Seção da Receita',
                'verbose_name_plural': 'Seções das Receitas',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='RecipeSectionIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(help_text='500, 2, 1/2...', max_length=50, verbose_name='Quantidade')),
                ('unit', models.CharField(choices=[('g', 'gramas'), ('kg', 'quilogramas'), ('mg', 'miligramas'), ('oz', 'onças (oz)'), ('lb', 'libras (lb)'), ('ml', 'mililitros'), ('l', 'litros'), ('xic', 'xícaras'), ('col_sopa', 'colheres de sopa'), ('col_cha', 'colheres de chá'), ('col_sob', 'colheres de sobremesa'), ('col_caf', 'colheres de café'), ('copo', 'copos'), ('pitada', 'pitadas'), ('fio', 'fios'), ('un', 'unidades'), ('dz', 'dúzias'), ('cento', 'centos'), ('pacote', 'pacotes'), ('lata', 'latas'), ('garrafa', 'garrafas'), ('caixa', 'caixas'), ('rendimento_livre', 'A gosto')], default='gramas', help_text='Medidas caseiras', max_length=20, verbose_name='Unidades de quantidade')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipesection')),
            ],
        ),
        migrations.AddField(
            model_name='recipesection',
            name='ingredients',
            field=models.ManyToManyField(related_name='sections', through='recipes.RecipeSectionIngredient', to='recipes.ingredient'),
        ),
    ]
