# Generated by Django 6.0.1 on 2026-02-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_ingredient_alter_recipe_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipesectioningredient',
            options={'ordering': ['ingredient'], 'verbose_name': 'Seção de receita por ingrediente', 'verbose_name_plural': 'Seções de receitas por ingredientes'},
        ),
        migrations.AddField(
            model_name='recipesectioningredient',
            name='note',
            field=models.CharField(blank=True, help_text='Ex: gelada, batida para a massa, para pincelar, etc.', max_length=250, null=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='serving_unit',
            field=models.CharField(choices=[('porcoes', 'Porções'), ('pessoas', 'Pessoas'), ('unidades', 'Unidades'), ('fatias', 'Fatias'), ('pedacos', 'Pedaços'), ('copos', 'Copos'), ('tacas', 'Taças'), ('pratos', 'Pratos'), ('un', 'Itens'), ('docinhos', 'Docinhos (Cento)'), ('salgadinhos', 'Salgadinhos (Cento)'), ('massa', 'Massa (kg)'), ('rendimento_livre', 'a gosto')], default='porcoes', help_text='Unidade de medida para as porções', max_length=20, verbose_name='Unidade de porção'),
        ),
        migrations.AlterField(
            model_name='recipesection',
            name='title',
            field=models.CharField(help_text='Ex: Massa, Recheio, Cobertura...', max_length=100, verbose_name='Nome da seção'),
        ),
        migrations.AlterField(
            model_name='recipesectioningredient',
            name='quantity',
            field=models.CharField(blank=True, help_text='Insira apenas o número (ex: 500, 2 e 1/2), sem a unidade de medida', max_length=50, null=True, verbose_name='Quantidade'),
        ),
    ]
