# Generated by Django 6.0.1 on 2026-02-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipesectioningredient_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipesectioningredient',
            name='unit',
            field=models.CharField(blank=True, choices=[('', 'N/A'), ('g', 'gramas'), ('kg', 'quilogramas'), ('mg', 'miligramas'), ('oz', 'onças (oz)'), ('lb', 'libras (lb)'), ('ml', 'mililitros'), ('l', 'litros'), ('xic', 'xícaras'), ('col_sopa', 'colheres de sopa'), ('col_cha', 'colheres de chá'), ('col_sob', 'colheres de sobremesa'), ('col_caf', 'colheres de café'), ('copo', 'copos'), ('pitada', 'pitadas'), ('fio', 'fios'), ('un', 'unidades'), ('dz', 'dúzias'), ('cento', 'centos'), ('pacote', 'pacotes'), ('lata', 'latas'), ('garrafa', 'garrafas'), ('caixa', 'caixas'), ('rendimento_livre', 'A gosto')], default='', help_text="Ex: gramas, unidades ou 'N/A' para nenhum.", max_length=20, null=True, verbose_name='Unidades de quantidade'),
        ),
    ]
