# Generated by Django 6.0.1 on 2026-02-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipesectioningredient_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time_unit',
            field=models.CharField(choices=[('s', 'segundo(s)'), ('min', 'minuto(s)'), ('h', 'hora(s)')], default='minutos', help_text='Unidade de medida do tempo de cozimento', max_length=20, verbose_name='Unidade de medida de cozimento'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='preparation_time_unit',
            field=models.CharField(choices=[('s', 'segundo(s)'), ('min', 'minuto(s)'), ('h', 'hora(s)')], default='minutos', help_text='Unidade de medida do tempo de preparo', max_length=20, verbose_name='Unidade de tempo de preparo'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='serving_unit',
            field=models.CharField(choices=[('porcoes', 'porção(ões)'), ('pessoas', 'pessoa(s)'), ('unidades', 'unidade(s)'), ('fatias', 'fatia(s)'), ('pedacos', 'pedaço(s)'), ('copos', 'copo(s)'), ('tacas', 'taça(s)'), ('pratos', 'prato(s)'), ('un', 'item(ns)'), ('docinhos', 'docinho(s) (cento)'), ('salgadinhos', 'salgadinho(s) (cento)'), ('massa', 'massa(s) (kg)'), ('rendimento_livre', 'a gosto')], default='porcoes', help_text='Unidade de medida para as porções', max_length=20, verbose_name='Unidade de porção'),
        ),
        migrations.AlterField(
            model_name='recipesectioningredient',
            name='unit',
            field=models.CharField(blank=True, choices=[('', 'N/A'), ('g', 'g'), ('kg', 'kg'), ('mg', 'mg'), ('oz', 'oz'), ('lb', 'lib'), ('ml', 'ml'), ('l', 'l'), ('cubo', 'cubo(s)'), ('xic', 'xícara(s)'), ('col_sopa', 'colher(es) de sopa'), ('col_cha', 'colher(es) de chá'), ('col_sob', 'colher(es) de sobremesa'), ('col_caf', 'colher(es) de café'), ('copo', 'copo(s)'), ('pitada', 'pitada(s)'), ('fio', 'fio(s)'), ('un', 'unidade(s)'), ('dz', 'dúzia(s)'), ('cento', 'cento(s)'), ('pacote', 'pacote(s)'), ('lata', 'lata(s)'), ('garrafa', 'garrafa(s)'), ('caixa', 'caixa(s)'), ('rendimento_livre', 'a gosto')], default='', help_text="Ex: gramas, unidades ou 'N/A' para nenhum.", max_length=20, null=True, verbose_name='Unidades de quantidade'),
        ),
    ]
