# Generated by Django 6.0.1 on 2026-02-03 17:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipe_cooking_time_unit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreparationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.TextField(verbose_name='Descrição da etapa')),
                ('position', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Etapa de preparo',
                'verbose_name_plural': 'Etapas de preparo',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='RecipeSectionPreparationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Etapa de preparo da seção',
                'verbose_name_plural': 'Etapas de preparo da seção',
            },
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Favorito', 'verbose_name_plural': 'Favoritos'},
        ),
        migrations.AlterModelOptions(
            name='reciperating',
            options={'verbose_name': 'Avaliação', 'verbose_name_plural': 'Avaliações'},
        ),
        migrations.AlterModelOptions(
            name='recipesection',
            options={'ordering': ['position'], 'verbose_name': 'Seção da receita', 'verbose_name_plural': 'Seções da receita'},
        ),
        migrations.AlterModelOptions(
            name='recipesectioningredient',
            options={'ordering': ['id'], 'verbose_name': 'Ingrediente da seção', 'verbose_name_plural': 'Ingredientes da seção'},
        ),
        migrations.RemoveIndex(
            model_name='favorite',
            name='recipes_fav_user_id_5d8c58_idx',
        ),
        migrations.RemoveIndex(
            model_name='favorite',
            name='recipes_fav_recipe__f749a7_idx',
        ),
        migrations.RemoveIndex(
            model_name='reciperating',
            name='recipes_rec_created_168e77_idx',
        ),
        migrations.RemoveIndex(
            model_name='reciperating',
            name='recipes_rec_rating_0277a4_idx',
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(help_text='Breve descrição da categoria (máx. 250 caracteres)', max_length=250, verbose_name='Descrição curta'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon_key',
            field=models.CharField(blank=True, default='utensils', help_text="Nome do ícone da biblioteca Lucide (ex: 'fish', 'cake'). Consulte lucide.dev", max_length=20, null=True, verbose_name='Ícone da categoria'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, help_text='Nome único para a categoria (máx. 65 caracteres)', max_length=65, unique=True, verbose_name='Nome da categoria'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Versão amigável para a URL (gerada automaticamente)', max_length=100, unique=True, verbose_name='Slug da URL'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='recipes.recipe'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ingredients/covers/%Y/%m/%d', verbose_name='Imagem do ingrediente'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nome do ingrediente'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Slug da URL'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(help_text='Usuário responsável pela criação desta receita', on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipes', to='recipes.category', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Tempo de cozimento'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time_unit',
            field=models.CharField(choices=[('s', 'segundo(s)'), ('min', 'minuto(s)'), ('h', 'hora(s)')], default='min', max_length=20, verbose_name='Unidade do tempo de cozimento'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/covers/%Y/%m/%d/', verbose_name='Imagem de capa'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.CharField(help_text='Resumo da receita para as listagens', max_length=500, verbose_name='Descrição curta'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='difficulty_level',
            field=models.CharField(choices=[('facil', 'Fácil'), ('medio', 'Médio'), ('dificil', 'Difícil'), ('expert', 'Expert / Profissional')], default='medio', max_length=10, verbose_name='Nível de dificuldade'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False, help_text='Se marcado, a receita ficará visível no site', verbose_name='Publicado'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='preparation_time',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Tempo de preparo'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='preparation_time_unit',
            field=models.CharField(choices=[('s', 'segundo(s)'), ('min', 'minuto(s)'), ('h', 'hora(s)')], default='min', max_length=20, verbose_name='Unidade do tempo de preparo'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='serving_unit',
            field=models.CharField(choices=[('porcoes', 'porção(ões)'), ('pessoas', 'pessoa(s)'), ('unidades', 'unidade(s)'), ('fatias', 'fatia(s)'), ('pedacos', 'pedaço(s)'), ('copos', 'copo(s)'), ('tacas', 'taça(s)'), ('pratos', 'prato(s)'), ('un', 'item(ns)'), ('docinhos', 'docinho(s) (cento)'), ('salgadinhos', 'salgadinho(s) (cento)'), ('massa', 'massa(s) (kg)'), ('rendimento_livre', 'a gosto')], default='porcoes', max_length=20, verbose_name='Unidade do rendimento'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='servings',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Rendimento'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Slug da URL'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Título da receita'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='reciperating',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comentário'),
        ),
        migrations.AlterField(
            model_name='reciperating',
            name='rating',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Avaliação'),
        ),
        migrations.AlterField(
            model_name='reciperating',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='recipes.recipe'),
        ),
        migrations.AlterField(
            model_name='reciperating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipesection',
            name='position',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ordem da seção'),
        ),
        migrations.RemoveField(
            model_name='recipesection',
            name='preparation_steps',
        ),
        migrations.AlterField(
            model_name='recipesection',
            name='title',
            field=models.CharField(help_text='Ex: Massa, Recheio, Cobertura', max_length=100, verbose_name='Título da seção'),
        ),
        migrations.AlterField(
            model_name='recipesectioningredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient', verbose_name='Ingrediente'),
        ),
        migrations.AlterField(
            model_name='recipesectioningredient',
            name='note',
            field=models.CharField(blank=True, help_text='Ex: gelada, picada, para pincelar', max_length=250, null=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='recipesectioningredient',
            name='quantity',
            field=models.CharField(blank=True, help_text='Ex: 500, 2 1/2, 1', max_length=50, null=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='recipesectioningredient',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipesection', verbose_name='Seção'),
        ),
        migrations.AlterField(
            model_name='recipesectioningredient',
            name='unit',
            field=models.CharField(blank=True, choices=[('', 'N/A'), ('g', 'g'), ('kg', 'kg'), ('mg', 'mg'), ('oz', 'oz'), ('lb', 'lb'), ('ml', 'ml'), ('l', 'l'), ('cubo', 'cubo(s)'), ('xic', 'xícara(s)'), ('col_sopa', 'colher(es) de sopa'), ('col_cha', 'colher(es) de chá'), ('col_sob', 'colher(es) de sobremesa'), ('col_caf', 'colher(es) de café'), ('copo', 'copo(s)'), ('pitada', 'pitada(s)'), ('fio', 'fio(s)'), ('un', 'unidade(s)'), ('dz', 'dúzia(s)'), ('cento', 'cento(s)'), ('pacote', 'pacote(s)'), ('lata', 'lata(s)'), ('garrafa', 'garrafa(s)'), ('caixa', 'caixa(s)'), ('rendimento_livre', 'a gosto')], default='', max_length=20, null=True, verbose_name='Unidade de medida'),
        ),
        migrations.AddField(
            model_name='recipesectionpreparationmethod',
            name='preparation_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.preparationmethod', verbose_name='Etapa de preparo'),
        ),
        migrations.AddField(
            model_name='recipesectionpreparationmethod',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipesection', verbose_name='Seção'),
        ),
        migrations.AddField(
            model_name='recipesection',
            name='preparation_steps',
            field=models.ManyToManyField(related_name='sections', through='recipes.RecipeSectionPreparationMethod', to='recipes.preparationmethod', verbose_name='Modo de preparo'),
        ),
    ]
