# Generated by Django 6.0.1 on 2026-02-03 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_preparationmethod_recipesectionpreparationmethod_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipesection',
            name='preparation_steps',
        ),
        migrations.AddField(
            model_name='preparationmethod',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='preparations', to='recipes.recipesection', verbose_name='Seção'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RecipeSectionPreparationMethod',
        ),
    ]
