# Generated by Django 6.0.1 on 2026-02-03 18:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_remove_recipesection_preparation_steps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preparationmethod',
            name='position',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ordem'),
        ),
        migrations.AlterField(
            model_name='recipesection',
            name='position',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ordem da seção'),
        ),
    ]
