# Generated by Django 6.0.1 on 2026-02-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_preparationmethod_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preparationmethod',
            name='step',
            field=models.CharField(help_text='Etapa do modo de preparo (máx. 255 caracteres)', max_length=255, verbose_name='Descrição da etapa'),
        ),
    ]
