# Generated by Django 6.0.1 on 2026-02-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_alter_preparationmethod_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='apps/recipes/ingredients/covers/%Y/%m/%d', verbose_name='Imagem do ingrediente'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='apps/recipes/covers/%Y/%m/%d/', verbose_name='Imagem de capa'),
        ),
    ]
