# Generated by Django 6.0.1 on 2026-02-03 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_alter_ingredient_image_alter_recipe_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ingredients/covers/%Y/%m/%d', verbose_name='Imagem do ingrediente'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/covers/%Y/%m/%d', verbose_name='Imagem de capa'),
        ),
    ]
