# Generated by Django 6.0.1 on 2026-02-03 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_alter_ingredient_image_alter_recipe_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, help_text='Breve descrição da categoria (máx. 250 caracteres)', max_length=250, null=True, verbose_name='Descrição curta'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='Versão amigável para a URL (gerada automaticamente)', max_length=100, null=True, unique=True, verbose_name='Slug da URL'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='Slug da URL'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='Slug da URL'),
        ),
    ]
