# Generated by Django 6.0.1 on 2026-02-03 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_alter_category_description_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipesectioningredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_in_sections', to='recipes.ingredient', verbose_name='Ingrediente'),
        ),
        migrations.AlterField(
            model_name='recipesectioningredient',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_ingredient', to='recipes.recipesection', verbose_name='Seção'),
        ),
    ]
