# Generated by Django 6.0.1 on 2026-02-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_alter_recipesectioningredient_ingredient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='views_count',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Número total de vezes que a receita foi visualizada', verbose_name='Visualizações'),
        ),
    ]
