# Generated by Django 6.0.1 on 2026-02-05 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_recipe_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/cover/%Y/%m/%d', verbose_name='Imagem da categoria'),
        ),
    ]
